language: python
python:
  - "2.7"
  - "3.3"

virtualenv:
  system_site_packages: true

before_install:
  - ci/before_install.sh

install:
  - pip install --use-mirrors numpy
  - pip install --use-mirrors scipy
  - pip install --use-mirrors oct2py
  - python setup.py install
script:
  - cd tests
  - nosetests --verbose --nocapture test_result_comparison.py

branches:
  only:
    - master
