language: python

env:
    - CONDA="python=2.7 numpy=1.7"
    - CONDA="python=3.3 numpy"
    - CONDA="python=3.4 numpy"

before_install:
    - sudo apt-add-repository -y ppa:picaso/octave;
    - sudo apt-get update -qq;
    - sudo apt-get install -qq octave liboctave-dev;
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes
    - conda update conda
    - conda info -a
    - travis_retry conda create -n test $CONDA numpy pip nose scipy
    - source activate test
    - travis_retry pip install coveralls
    - travis_retry pip install oct2py

install:
    - export PYTHONWARNINGS=all
    - python setup.py install

script:
    # run coverage on py2.7, regular on others.
    - if [[ $CONDA == python=2.7* ]]; then
        nosetests --verbose --with-doctest --with-cov --cover-package seawater
    else
        nosetests --verbose seawater
    fi

after_success:
    - coveralls
